# Hospital Management SQL Analysis
## Business Intelligence Project using SQL, SQLite & Python

#### Project Objective

This project analyzes a hospital management database to answer real-world business questions using SQL. The analysis focuses on hospital operations, patient trends, doctor performance, appointment management, and revenue generation. SQL queries are executed through SQLite in Jupyter Notebook using Python and Pandas.

## 1. Import Required Libraries
Import the Python libraries required to load datasets, create an SQLite database, and execute SQL queries.s.

In [1]:
import pandas as pd 
import sqlite3

## 2. Load the Hospital Dataset
Load all CSV files into Pandas DataFrames for further inspection and SQL database creation.e.

In [5]:
patients = pd.read_csv("../Data/patients.csv")
doctors = pd.read_csv("../Data/doctors.csv")
billing = pd.read_csv("../Data/billing.csv")
treatments = pd.read_csv("../Data/treatments.csv")
appointments= pd.read_csv("../Data/appointments.csv")

In [84]:
patients["registration_date"] = pd.to_datetime(patients["registration_date"])
patients["date_of_birth"] = pd.to_datetime(patients["date_of_birth"])
appointments["appointment_date"] = pd.to_datetime(appointments["appointment_date"])
billing["bill_date"] = pd.to_datetime(billing["bill_date"])
treatments["treatment_date"] = pd.to_datetime(treatments["treatment_date"])

## 3. Data Quality Assessment
Perform an initial assessment of each dataset by checking its structure, data types, missing values, and overall quality before loading it into the SQL database.e.

#### 3.1 Patients Dataset Review
Inspect the Patients dataset to verify data types, identify missing values, and understand the available attributes.

In [6]:
patients.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com

In [7]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     object
 1   first_name          50 non-null     object
 2   last_name           50 non-null     object
 3   gender              50 non-null     object
 4   date_of_birth       50 non-null     object
 5   contact_number      50 non-null     int64
 6   address             50 non-null     object
 7   registration_date   50 non-null     object
 8   insurance_provider  50 non-null     object
 9   insurance_number    50 non-null     object
 10  email               50 non-null     object
dtypes: int64(1), object(10)
memory usage: 4.4+ KB

In [8]:
patients.shape

(50, 11)

In [9]:
patients.columns.tolist()

['patient_id',
 'first_name',
 'last_name',
 'gender',
 'date_of_birth',
 'contact_number',
 'address',
 'registration_date',
 'insurance_provider',
 'insurance_number',
 'email']

In [10]:
patients.describe()

       contact_number
count    5.000000e+01
mean     7.817283e+09
std      9.573594e+08
min      6.141952e+09
25%      7.065593e+09
50%      7.749927e+09
75%      8.599947e+09
max      9.900972e+09

In [11]:
patients.isnull().sum()

patient_id            0
first_name            0
last_name             0
gender                0
date_of_birth         0
contact_number        0
address               0
registration_date     0
insurance_provider    0
insurance_number      0
email                 0
dtype: int64

In [83]:
patients.dtypes

patient_id                    object
first_name                    object
last_name                     object
gender                        object
date_of_birth                 object
contact_number                 int64
address                       object
registration_date     datetime64[ns]
insurance_provider            object
insurance_number              object
email                         object
dtype: object

In [58]:
patients["insurance_provider"].unique()

array(['WellnessCorp', 'PulseSecure', 'HealthIndia', 'MedCare Plus'],
      dtype=object)

Observation:
The Patients table contains 50 records with 11 attributes. No missing values were identified, indicating that the dataset is complete and suitable for SQL analysis.

#### 3.2 Doctors Dataset Review

In [14]:
doctors.head()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com

In [15]:
doctors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     object
 1   first_name        10 non-null     object
 2   last_name         10 non-null     object
 3   specialization    10 non-null     object
 4   phone_number      10 non-null     int64
 5   years_experience  10 non-null     int64
 6   hospital_branch   10 non-null     object
 7   email             10 non-null     object
dtypes: int64(2), object(6)
memory usage: 768.0+ bytes

In [17]:
doctors.shape

(10, 8)

In [18]:
doctors.columns.tolist()

['doctor_id',
 'first_name',
 'last_name',
 'specialization',
 'phone_number',
 'years_experience',
 'hospital_branch',
 'email']

In [19]:
doctors.describe()

       phone_number  years_experience
count  1.000000e+01           10.0000
mean   7.919716e+09           21.5000
std    1.142890e+09            6.7536
min    6.176384e+09            5.0000
25%    6.792438e+09           19.5000
50%    8.269752e+09           23.5000
75%    8.937722e+09           26.0000
max    9.118539e+09           28.0000

In [20]:
doctors.isnull().sum()

doctor_id           0
first_name          0
last_name           0
specialization      0
phone_number        0
years_experience    0
hospital_branch     0
email               0
dtype: int64

In [21]:
doctors.dtypes

doctor_id           object
first_name          object
last_name           object
specialization      object
phone_number         int64
years_experience     int64
hospital_branch     object
email               object
dtype: object

In [53]:
doctors['hospital_branch'].unique()

array(['Westside Clinic', 'Eastside Clinic', 'Central Hospital'],
      dtype=object)

Observation :
The Doctors dataset contains doctor profiles and specialization information with no missing values.

### 3.3 Billing Dataset Review

In [22]:
billing.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [23]:
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_id         200 non-null    object
 1   patient_id      200 non-null    object
 2   treatment_id    200 non-null    object
 3   bill_date       200 non-null    object
 4   amount          200 non-null    float64
 5   payment_method  200 non-null    object
 6   payment_status  200 non-null    object
dtypes: float64(1), object(6)
memory usage: 11.1+ KB

In [25]:
billing.shape

(200, 7)

In [26]:
billing.columns.tolist()

['bill_id',
 'patient_id',
 'treatment_id',
 'bill_date',
 'amount',
 'payment_method',
 'payment_status']

In [27]:
billing.describe()

            amount
count   200.000000
mean   2756.249250
std    1298.125308
min     534.030000
25%    1563.412500
50%    2828.165000
75%    3836.627500
max    4973.630000

In [28]:
billing.isnull().sum()

bill_id           0
patient_id        0
treatment_id      0
bill_date         0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [29]:
billing.dtypes

bill_id            object
patient_id         object
treatment_id       object
bill_date          object
amount            float64
payment_method     object
payment_status     object
dtype: object

In [49]:
billing['payment_status'].unique()

array(['Pending', 'Paid', 'Failed'], dtype=object)

Observation:
The Billing dataset contains billing amount, payment method, and payment status required for revenue analysis.

### 3.4 Treatments Dataset Review

In [30]:
treatments.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06

In [31]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   treatment_id    200 non-null    object
 1   appointment_id  200 non-null    object
 2   treatment_type  200 non-null    object
 3   description     200 non-null    object
 4   cost            200 non-null    float64
 5   treatment_date  200 non-null    object
dtypes: float64(1), object(5)
memory usage: 9.5+ KB

In [33]:
treatments.shape

(200, 6)

In [34]:
treatments.describe()

              cost
count   200.000000
mean   2756.249250
std    1298.125308
min     534.030000
25%    1563.412500
50%    2828.165000
75%    3836.627500
max    4973.630000

In [35]:
treatments.columns.tolist()

['treatment_id',
 'appointment_id',
 'treatment_type',
 'description',
 'cost',
 'treatment_date']

In [36]:
treatments.isnull().sum()

treatment_id      0
appointment_id    0
treatment_type    0
description       0
cost              0
treatment_date    0
dtype: int64

In [37]:
treatments.dtypes

treatment_id       object
appointment_id     object
treatment_type     object
description        object
cost              float64
treatment_date     object
dtype: object

In [47]:
treatments["description"].unique()

array(['Basic screening', 'Advanced protocol', 'Standard procedure'],
      dtype=object)

Observation : 
The Treatments dataset links appointments with medical procedures and acts as an intermediate table for revenue analysis..

### 3.5 Appointments Dataset Review

In [38]:
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

In [39]:
appointments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    object
 1   patient_id        200 non-null    object
 2   doctor_id         200 non-null    object
 3   appointment_date  200 non-null    object
 4   appointment_time  200 non-null    object
 5   reason_for_visit  200 non-null    object
 6   status            200 non-null    object
dtypes: object(7)
memory usage: 11.1+ KB

In [41]:
appointments.columns.tolist()

['appointment_id',
 'patient_id',
 'doctor_id',
 'appointment_date',
 'appointment_time',
 'reason_for_visit',
 'status']

In [43]:
appointments.isnull().sum()

appointment_id      0
patient_id          0
doctor_id           0
appointment_date    0
appointment_time    0
reason_for_visit    0
status              0
dtype: int64

In [45]:
appointments.dtypes

appointment_id      object
patient_id          object
doctor_id           object
appointment_date    object
appointment_time    object
reason_for_visit    object
status              object
dtype: object

In [60]:
appointments["reason_for_visit"].unique()

array(['Therapy', 'Consultation', 'Emergency', 'Checkup', 'Follow-up'],
      dtype=object)

Observation :
The Appointments dataset contains scheduling information including doctor assignment, patient assignment, appointment status, and appointment dates.

## 4. Create SQLite Database

SQLite is a lightweight relational database that stores multiple related tables in a single database file

In this step, all pandas DataFrames are transferred into a SQLite database (`hospital.db`) to enable SQL querying.

In [61]:
conn = sqlite3.connect("../database/hospital.db")

In [62]:
patients.to_sql("patients", conn, if_exists ="replace" , index = False ) 
doctors. to_sql("doctors", conn , if_exists = "replace" , index = False)
billing. to_sql("billing", conn , if_exists = "replace" , index = False)
treatments.to_sql("treatments",conn, if_exists= "replace" , index = False)
appointments.to_sql("appointments", conn , if_exists = "replace" , index = False)

200

## 5. Verify Database Structure
**Purpose**
Confirm that all tables have been successfully imported into SQLite before beginning SQL analysis.dles.

In [63]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, con

           name
0      patients
1       doctors
2       billing
3    treatments
4  appointments

## 6. SQL Business Analysis

**Business Objective**
Answer real-world hospital business questions using SQL queries and translate the results into meaningful business insights.ase.

### Section 1 — Hospital Key Performance Indicators (KPIs)

**Objective**
Evaluate the overall performance of the hospital using essential operational metrics.

#### Business Question 1
**Manager's Question**

How many patients are currently registered in the hospital database?

In [66]:
query = """
SELECT count(*)
FROM patients
"""
pd.read_sql(query, conn)

   count(*)
0        50

Observation : The query returns the total number of registered patients in the hospital database. This KPI helps management understand the current size of the patient base.

**Business Insight**

This metric provides an overview of the hospital's patient base and serves as a baseline KPI.

#### Business Question 2
**Manager's Question**

How many doctors do we currently have?

In [67]:
query = """
SELECT count(*)
FROM doctors
"""
pd.read_sql(query, conn)

   count(*)
0        10

**Observation** : 
This query returns the total number of doctors currently available in the hospital.

**Business Insight** :
Understanding the size of the medical workforce helps hospital management evaluate staffing capacity and plan future recruitment if required.

#### Business Question 3
**Manager's Question**

How many appointments have been completed, cancelled, scheduled, and no-show?

In [69]:
query = """
SELECT status , count(*)
FROM appointments
GROUP BY status;
"""
pd.read_sql(query, conn)

      status  count(*)
0  Cancelled        51
1  Completed        46
2    No-show        52
3  Scheduled        51

**Observation** :
The query summarizes appointments by their current status, such as Completed, Cancelled, and No-show.

**Business Insight** :Monitoring appointment status helps identify operational efficiency, patient attendance patterns, and potential scheduling issues.

#### Business Question 4
**Manager's Question**

How many patients are registered under each insurance provider?

In [70]:
query = """
SELECT insurance_provider, count(*)
FROM patients
GROUP BY insurance_provider;
"""
pd.read_sql(query, conn)

  insurance_provider  count(*)
0        HealthIndia         6
1       MedCare Plus        18
2        PulseSecure        10
3       WellnessCorp        16

**Observation** : 
The query groups patients according to their insurance provider.

**Business Insight** : 
This analysis helps identify the hospital's major insurance partners and supports strategic decisions regarding insurance collaborations.

#### Business Question 5
**Manager's Question**

Which insurance provider has the highest number of registered patients?

In [73]:
query = """
SELECT insurance_provider, count(*)
FROM patients
GROUP BY insurance_provider
ORDER BY count(*) DESC;
"""
pd.read_sql(query, conn)

  insurance_provider  count(*)
0       MedCare Plus        18
1       WellnessCorp        16
2        PulseSecure        10
3        HealthIndia         6

**Observation** : 
The query identifies the insurance provider associated with the largest number of registered patients.

**Business Insight** : 
Recognizing the most common insurance provider helps the hospital strengthen relationships with key insurance partners and negotiate better agreements.

### Section 2 — Patient Analytics

Objective

Analyze patient demographics, registration trends, and appointment behavior to better understand the hospital's patient population.

#### Business Question 6
**Manager's Question**

Show me every appointment along with the patient's first and last name.

In [78]:
query = """
SELECT appointment_id,first_name,last_name,appointment_date,status
FROM appointments
LEFT JOIN patients
ON appointments.patient_id =patients.patient_id;
"""
pd.read_sql(query, conn)

    appointment_id first_name last_name appointment_date     status
0             A001       Alex     Smith       2023-08-09  Scheduled
1             A002       Alex     Moore       2023-06-09    No-show
2             A003      Emily    Miller       2023-06-28  Cancelled
3             A004     Robert    Wilson       2023-09-01  Cancelled
4             A005      Emily  Williams       2023-07-06    No-show
..             ...        ...       ...              ...        ...
195           A196      Linda    Miller       2023-10-26  Cancelled
196           A197      David  Williams       2023-04-01    No-show
197           A198       John     Brown       2023-05-15    No-show
198           A199       Jane     Jones       2023-05-01  Completed
199           A200       Alex   Johnson       2023-12-30  Cancelled

[200 rows x 5 columns]

**Observation** : 
The query displays appointment details along with each patient's full name.

**Business Insight** : 
Combining patient information with appointment records creates a more meaningful and readable operational report for hospital staff.

#### Business Question 7
**Manager's Question**

How many male and female patients are registered in the hospital?

In [79]:
query = """
SELECT gender , count(*)
FROM patients
GROUP BY gender;
"""
pd.read_sql(query, conn)

  gender  count(*)
0      F        19
1      M        31

**Observation** : 
The query compares the number of male and female patients registered in the hospital.

**Business Insight** :
Gender distribution analysis supports demographic studies and assists in planning specialized healthcare services.g.

#### Business Question 8
**Manager's Question**


Which patients registered most recently?

In [85]:
query = """
SELECT first_name ,last_name, patient_id, registration_date 
FROM patients
ORDER BY registration_date DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

  first_name last_name patient_id registration_date
0       Alex    Taylor       P014        2023-12-12
1    Michael    Wilson       P033        2023-09-06
2      David    Wilson       P035        2023-07-09
3      Sarah    Miller       P019        2023-06-24
4      Emily    Miller       P048        2023-06-19
5       Alex     Smith       P034        2023-06-18
6      David     Moore       P049        2023-06-14
7       Alex     Moore       P028        2023-05-20
8      Laura    Wilson       P050        2023-04-28
9      Laura     Davis       P012        2023-04-27

**Observation** : 
The query summarizes patient registrations over time based on registration dates.

**Business Insight** : 
Registration trends help management understand patient growth patterns and evaluate the effectiveness of outreach initiatives.

#### Business Question 9
**Manager's Question**

Who are the oldest and youngest patients in our hospital?

In [88]:
# yougest 
query = """
SELECT first_name, last_name, date_of_birth
FROM patients
ORDER BY date_of_birth DESC
LIMIT 1;
"""
pd.read_sql(query, conn)

  first_name last_name date_of_birth
0      David     Smith    2005-05-15

In [89]:
# oldest
query = """
SELECT first_name, last_name, date_of_birth
FROM patients
ORDER BY date_of_birth 
LIMIT 1;
"""
pd.read_sql(query, conn)

  first_name last_name date_of_birth
0       Alex     Smith    1950-01-26

**Observation** : 
The query identifies the oldest and youngest patients in the database.

**Business Insight** :
Age distribution provides valuable information for planning age-specific healthcare services and resource allocation.

#### Business Question 10
**Manager's Question**

Show me all patients who have never booked an appointment.

In [101]:

query = """
SELECT patients.patient_id , patients.first_name,patients.last_name ,appointments.appointment_id
FROM patients
LEFT JOIN appointments
ON patients.patient_id = appointments.patient_id
WHERE appointments.appointment_id is null;
"""
pd.read_sql(query, conn)

  patient_id first_name last_name appointment_id
0       P006      Linda     Jones           None
1       P015      Sarah   Johnson           None

**Observation** : 
The query identifies registered patients who have not yet booked any appointments.

**Business Insight** : 
These patients may require follow-up communication or appointment reminders to improve patient engagement.s.

#### Business Question 11
**Manager's Question**

Show the complete doctor directory including doctor's name, specialization, and hospital branch

In [102]:

query = """
SELECT *
FROM doctors;
"""
pd.read_sql(query, conn)

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com
5,D006,Alex,Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com
6,D007,Robert,Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com
7,D008,Linda,Brown,Dermatology,9069162601,5,Westside Clinic,dr.linda.brown@hospital.com
8,D009,Sarah,Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com
9,D010,Linda,Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com

**Observation** : 
The query displays all doctors along with their respective medical specializations.

**Business Insight** : 
This information provides a structured overview of the hospital's medical expertise and supports workforce planning.

#### Business Question 12
**Manager's Question**

Which doctors are the busiest? Show the number of appointments handled by each doctor

In [181]:

query = """
SELECT doctors.doctor_id ,doctors.first_name,doctors.last_name,doctors.specialization,count(appointments.appointment_id) AS appointment_count
FROM doctors
LEFT JOIN appointments
ON doctors.doctor_id = appointments.doctor_id
GROUP BY doctors.doctor_id
ORDER BY count(appointments.appointment_id) DESC;
"""
pd.read_sql(query, conn)

  doctor_id first_name last_name specialization  appointment_count
0      D005      Sarah    Taylor    Dermatology                 29
1      D001      David    Taylor    Dermatology                 25
2      D006       Alex     Davis     Pediatrics                 24
3      D003       Jane     Smith     Pediatrics                 22
4      D002       Jane     Davis     Pediatrics                 21
5      D010      Linda    Wilson       Oncology                 19
6      D009      Sarah     Smith     Pediatrics                 17
7      D008      Linda     Brown    Dermatology                 16
8      D004      David     Jones     Pediatrics                 14
9      D007     Robert     Davis       Oncology                 13

**Observation** : 
The query counts the number of appointments handled by every doctor. Busiest doctor is dr sarah taylor of dermatology department with appointment count of 29.

**Business Insight** : 
Doctor workload analysis helps management evaluate resource utilization and identify uneven appointment distribution.

#### Business Question 13
**Manager's Question**

Show every appointment along with the patient's name, doctor's name, doctor's specialization, appointment date, and appointment status.

In [119]:

query = """
SELECT appointments.appointment_id , patients.first_name AS Patient_first_name,patients.last_name AS Patient_last_name,doctors.first_name  AS Doctor_first_name,doctors.last_name AS Doctor_Last_name,doctors.specialization,appointments.appointment_date,appointments.status
FROM appointments
LEFT JOIN patients
ON appointments.patient_id = patients.patient_id 
LEFT JOIN doctors 
ON appointments.doctor_id = doctors.doctor_id;
"""
pd.read_sql(query, conn)

,appointment_id,Patient_first_name,Patient_last_name,Doctor_first_name,Doctor_Last_name,specialization,appointment_date,status
0,A001,Alex,Smith,Sarah,Smith,Pediatrics,2023-08-09,Scheduled
1,A002,Alex,Moore,David,Jones,Pediatrics,2023-06-09,No-show
2,A003,Emily,Miller,David,Jones,Pediatrics,2023-06-28,Cancelled
3,A004,Robert,Wilson,Alex,Davis,Pediatrics,2023-09-01,Cancelled
4,A005,Emily,Williams,Jane,Smith,Pediatrics,2023-07-06,No-show
...,...,...,...,...,...,...,...,...
195,A196,Linda,Miller,Alex,Davis,Pediatrics,2023-10-26,Cancelled
196,A197,David,Williams,Sarah,Taylor,Dermatology,2023-04-01,No-show
197,A198,John,Brown,Alex,Davis,Pediatrics,2023-05-15,No-show
198,A199,Jane,Jones,David,Taylor,Dermatology,2023-05-01,Completed
199,A200,Alex,Johnson,Sarah,Taylor,Dermatology,2023-12-30,Cancelled

**Observation** : 
This report combines appointment, patient, and doctor information into a single view. 

**Business insight** :
It provides hospital staff with meaningful appointment details by replacing patient and doctor IDs with names, making scheduling and monitoring easier.

#### Business Question 14
**Manager's Question**

Are there any doctors who have never handled an appointment?

In [189]:

query = """
SELECT doctors.doctor_id,doctors.first_name,doctors.last_name,doctors.specialization,appointments.appointment_id
FROM doctors
LEFT JOIN appointments
ON doctors.doctor_id = appointments.doctor_id
WHERE appointments.appointment_id is null;
"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [doctor_id, first_name, last_name, specialization, appointment_id]
Index: []

**Observation** : 
The query identifies doctors who currently have no scheduled appointments.

**Business Insight** : 
Doctors without appointments may indicate underutilized resources or opportunities to improve patient allocation.

### Section 4 — Appointment Analysis

**Objective**

Analyze appointment outcomes, scheduling trends, cancellations, and no-show rates to assess operational efficiency.

#### Business Question 15
**Manager's Question**

How many appointments are Completed, Cancelled, Scheduled, and No-show?

In [122]:

query = """
SELECT status , count(*)
FROM appointments
GROUP BY status;
"""
pd.read_sql(query, conn)

      status  count(*)
0  Cancelled        51
1  Completed        46
2    No-show        52
3  Scheduled        51

**Observation** : 
The appointment distribution is relatively balanced across all four statuses. However, the number of **No-show appointments (52)** is slightly higher than the number of **Completed appointments (46)**. This may indicate a potential patient attendance issue, suggesting the hospital could benefit from reminder calls, SMS notifications, or appointment confirmation systems to reduce no-shows.

#### Business Question 16
**Manager's Question**

How many appointments were scheduled each day?

In [129]:

query = """
SELECT appointment_date,count (*)
FROM appointments
GROUP BY appointment_date
ORDER BY appointment_date;
"""
pd.read_sql(query, conn)

    appointment_date  count (*)
0         2023-01-01          2
1         2023-01-02          1
2         2023-01-03          1
3         2023-01-05          1
4         2023-01-06          1
..               ...        ...
153       2023-12-18          1
154       2023-12-20          1
155       2023-12-24          1
156       2023-12-26          2
157       2023-12-30          1

[158 rows x 2 columns]

**Observation** : 
The query calculates the total number of appointments scheduled for each day.

**Business Insight** : 
Daily appointment trends help hospital administrators identify busy periods and allocate resources more efficiently.

#### Business Question 17
**Manager's Question**

What percentage of appointments are No-show?

In [133]:
query = """
SELECT 
sum(CASE WHEN status='No-show' THEN 1 ELSE 0 END) * 100.0 / count(*) AS no_show_percentage
FROM appointments;
"""
pd.read_sql(query, conn)

   no_show_percentage
0                26.0

**Observation** : 
The query calculates the percentage of appointments where patients did not attend.

**Business Insight** : 
A high no-show rate can negatively affect operational efficiency and may indicate the need for appointment reminder systems.

#### Business Question 18
**Manager's Question**

No-show % by doctor

In [137]:
query = """
SELECT doctors.doctor_id , doctors.first_name,doctors.last_name,
sum(CASE WHEN appointments.status='No-show' THEN 1 ELSE 0 END) * 100.0 / count(*) AS no_show_percentage
FROM doctors
LEFT JOIN appointments
ON doctors.doctor_id = appointments.doctor_id
GROUP BY doctors.doctor_id , doctors.first_name,doctors.last_name
ORDER BY no_show_percentage DESC;
"""
pd.read_sql(query, conn)

  doctor_id first_name last_name  no_show_percentage
0      D004      David     Jones           35.714286
1      D009      Sarah     Smith           35.294118
2      D003       Jane     Smith           31.818182
3      D005      Sarah    Taylor           31.034483
4      D001      David    Taylor           28.000000
5      D010      Linda    Wilson           26.315789
6      D006       Alex     Davis           25.000000
7      D008      Linda     Brown           25.000000
8      D007     Robert     Davis           15.384615
9      D002       Jane     Davis            4.761905

**Observation** : 
The query calculates the percentage of appointments marked as No-show for each doctor by comparing missed appointments against the total appointments handled by that doctor.

**Business Insight** : 
Comparing no-show rates across doctors helps identify scheduling patterns and patient attendance behavior. Doctors with consistently higher no-show percentages may benefit from improved appointment reminder systems, scheduling adjustments, or patient follow-up initiatives.

#### Business Question 19
**Manager's Question**

Top 3 Doctors with Highest Cancellation Rate

In [147]:
query = """
SELECT d.doctor_id , d.first_name, d.last_name, 
sum(CASE WHEN a.status='Cancelled' THEN 1 ELSE 0 END)*100.0 / count(a.appointment_id)  cancellation_rate
FROM doctors d 
LEFT JOIN appointments a 
ON d.doctor_id =a.doctor_id
GROUP BY  d.doctor_id , d.first_name, d.last_name
ORDER BY cancellation_rate DESC
LIMIT 3;
"""
pd.read_sql(query, conn)

  doctor_id first_name last_name  cancellation_rate
0      D007     Robert     Davis          38.461538
1      D002       Jane     Davis          38.095238
2      D008      Linda     Brown          31.250000

**Observation** : 
The query identifies the three doctors with the highest percentage of cancelled appointments based on their total scheduled appointments.

**Business Insight** : 
A high cancellation rate may indicate scheduling conflicts, frequent rescheduling, or operational inefficiencies. Identifying these doctors allows hospital management to investigate underlying causes and implement strategies to improve appointment reliability and patient satisfaction.

### Section 5 — Billing and Revenue Analysis

Objective

Evaluate hospital revenue, payment methods, insurance contributions, and doctor-wise revenue generation using collected billing data.

#### Business Question 20
**Manager's Question**

What is the total revenue collected by the hospital?

In [150]:
query = """
SELECT sum(amount)
FROM billing 
WHERE payment_status = 'Paid';
"""
pd.read_sql(query, conn)

   sum(amount)
0     173424.9

**Observation** : 
The query calculates the total revenue from successfully paid bills.

**Business Insight** : 
Total collected revenue is one of the hospital's most important financial KPIs and reflects actual income generated.

#### Business Question 21
**Manager's Question**

Which payment methods are generating the most collected revenue?

In [165]:
query = """
SELECT payment_method,SUM(amount) AS total_amount
FROM billing
WHERE payment_status='Paid'
GROUP BY payment_method
ORDER BY total_amount DESC;
"""
pd.read_sql(query, conn)

  payment_method  total_amount
0    Credit Card      60377.11
1      Insurance      60356.49
2           Cash      52691.30

**Observation** : 
The query summarizes collected revenue for each payment method with credit card with highest.

**Business Insight** : 
Understanding payment method preferences helps optimize payment services and improve patient convenience.

#### Business Question 22
**Manager's Question**

Which insurance provider has generated the highest collected revenue?

In [171]:
query = """
SELECT p.insurance_provider ,sum(b.amount) AS total_amount
FROM patients p
LEFT JOIN billing b
ON p.patient_id =b.pa
WHERE b.payment_status ='Paid'
GROUP BY p.insurance_provider 
ORDER BY total_amount DESC
LIMIT 1;
"""
pd.read_sql(query, conn)

  insurance_provider  total_amount
0       MedCare Plus      81109.48

**Observation** : 
The query identifies the revenue generated by insurance provider with max revenue.

**Business Insight** : 
This analysis highlights the hospital's most valuable insurance partnerships and supports strategic financial planning.

#### Business Question 23
**Manager's Question**

Which doctors generate the highest collected revenue?

In [179]:
query = """
SELECT  d.doctor_id , d.first_name,d.last_name , SUM(b.amount) AS Total_amount
FROM doctors d
LEFT JOIN appointments a 
ON d.doctor_id = a.doctor_id
LEFT JOIN treatments t 
ON a.appointment_id = t.appointment_id
LEFT JOIN billing b 
ON t.treatment_id = b.treatment_id
WHERE b.payment_status='Paid'
GROUP BY d.doctor_id , d.first_name,d.last_name
ORDER BY Total_amount DESC;
"""
pd.read_sql(query, conn)

  doctor_id first_name last_name  Total_amount
0      D005      Sarah    Taylor      33836.91
1      D006       Alex     Davis      25698.80
2      D010      Linda    Wilson      18935.50
3      D001      David    Taylor      18572.75
4      D002       Jane     Davis      18201.70
5      D004      David     Jones      17693.42
6      D003       Jane     Smith      17260.25
7      D008      Linda     Brown      12919.88
8      D009      Sarah     Smith       9230.98
9      D007     Robert     Davis       1074.71

**Observation** : 
The query calculates the total revenue collected from successful (Paid) billing records for each doctor and ranks them in descending order.

**Business Insight** : 
Doctor-wise revenue analysis helps evaluate financial performance across the medical staff. This information supports strategic decision-making related to resource allocation, departmental planning, performance evaluation, and understanding which specialties or doctors contribute most to the hospital's revenue.

#### Business Question 24
**Manager's Question**

Which payment method is used the most by patients?

In [188]:
query = """
SELECT payment_method, count(payment_method) AS Total_transaction
FROM billing
GROUP BY payment_method
ORDER BY Total_transaction DESC
LIMIT 1;
"""
pd.read_sql(query, conn)

  payment_method  Total_transaction
0    Credit Card                 75

**Observation** : 
The query identifies the payment method with the highest number of successful transactions.

**Business Insight** : 
Understanding the most preferred payment method helps the hospital prioritize secure and convenient payment options for patients.

#### Business Question 25
**Manager's Question**

What is the average revenue collected per successful payment?

In [187]:
query = """
SELECT AVG(amount) AS average_revenue
FROM billing
WHERE payment_status='Paid';
"""
pd.read_sql(query, conn)

   average_revenue
0      2709.764062

**Observation** : 
The query calculates the average amount collected from each successful payment transaction.

**Business Insight** : 
Monitoring the average payment value helps evaluate billing performance and provides a benchmark for future financial analysis.

## Project Conclusion

This project analyzed a hospital management database using SQL to solve 25 business-oriented questions across five analytical areas:

Hospital KPIs
Patient Analytics
Doctor Performance
Appointment Analysis
Billing and Revenue

Throughout the project, SQL was used to extract meaningful insights from multiple related tables. The analysis involved filtering, aggregation, conditional aggregation, joins, multi-table joins, sorting, grouping, and business KPI calculations.

#### Key SQL Concepts Applied
SELECT ,
WHERE ,
GROUP BY ,
ORDER BY ,
LIMIT ,
Aggregate Functions (COUNT, SUM, AVG) ,
CASE WHEN ,
INNER JOIN ,
LEFT JOIN ,
Multi-table JOINs ,
Business KPI Reporting .

#### Business Value

The project demonstrates how SQL can be used to support hospital decision-making by monitoring operational performance, patient trends, doctor productivity, appointment efficiency, and revenue generation.